### ISSUE TITLE
not working with apple silicon

### ISSUE THREAD

**Issue by jonathanstanley** [mosen/mysides#25]
i've used mysides for my last few macs, but it failed when trying with my m1 processor mac.  it may not be compatible with apple silicon as-is.

**Comment by fharper** [comment]
I have no issues on my M1. What is happening? Can you give more details. I'm not the maintainer but since it's working for me, I may be able to help.

**Comment by jonathanstanley** [comment]
Thanks for following up, however I dropped it from my setup and can't test it anymore.  Perhaps one its dependencies have since resolved and this is no longer an issue.

**Comment by mosen** [comment]
Don't have an m1 to recompile but ill give it a go
