### ISSUE TITLE
M1 Macs / Ventura

### ISSUE THREAD

**Issue by straxhaber** [mosen/mysides#27]
If it isn't too difficult, would you mind rebuilding this for M1 Macs? Right now, running it generates this error:
`/usr/local/bin/mysides: Bad CPU type in executable`

**Comment by mosen** [comment]
Can do, dont have a recent Xcode for the universal binary but will get it set up

**Comment by huyz** [comment]
I have an M1 Mac with Ventura and the v1.0.1 binary from `brew install mysides` works just fine.

**Comment by straxhaber** [comment]
It's working for me now, too. I'm not sure what was going on before, but we can mark this issue resolved as I can't reproduce the issue.

**Comment by ashtonian** [comment]
can confirm, this was *NOT* working for me but is now...

**Comment by johnliu** [comment]
For anyone looking at this more recently -- you need to install rosetta

```
softwareupdate --install-rosetta
```
