### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by jimhuls** [mosen/mysides#4]
I'm new to using github so my answer might be staring me in the face. 

Is there any sort of license attached to mysides? I do tech support at a community college and for a project I needed to create a solution that would mount a network drive and then place the mounted drive in the finder sidebar. Your mysides command worked perfect. To use it though means us distributing it to our endusers which would include a few home systems connected via vpn. 

Can we legally do this? It won't be of much use if the user has to come to github to get this as for most of our users, that'll be too complex of a process. The method I'm looking at is it being packaged with our application which is nothing more than a script that does the mounting and makes use of mysides.

Thanks!

**Comment by mosen** [comment]
Hey there,
I havent added a license to the project but I usually default to MIT because often people want to use this stuff in a commercial setting. Does that sound ok to you?

**Comment by jimhuls** [comment]
I'm really not all that familiar of the ins and outs of licenses since someone else is typically purchasing software that I install and support. My hope was to have an installer that included mysides. In doing some quick reading this morning it looks like this license is talking about including a readme. Our endusers would just be confused by this...or should I be reading that as you include a readme in your distribution? This is all new for me but we want to do it right but in a way that doesn't create issues with our users. Hope that makes sense.

**Comment by mosen** [comment]
Sorry for the late reply. I will be uploading an installer pkg for mysides 1.0.0 which includes the MIT license. You don't have to do anything on your end, i just include the LICENSE file.
