### ISSUE TITLE
Add ability to point at another users file space

### ISSUE THREAD

**Issue by lazymutt** [mosen/mysides#7]
I'd really like the ability to direct _mysides_ to modify **another** users Finder prefs.

**Comment by jimratliff** [comment]
Couldn't you just use `su` to execute mysides as if logged in as the other user?

`su - other_user_name -c 'mysides add example file:///Users/Shared/example'`

or something like that?

**Comment by lazymutt** [comment]
That's what I ended up doing after some additional thought. Should have closed this isuue.
