### ISSUE TITLE
Exit Code when Adding Sidebar Item Doesn't Produce a 0 ...

### ISSUE THREAD

**Issue by apizz** [mosen/mysides#9]
I was working on scripting something for our users when they login for the first time, but for some reason even though I get an "Added sidebar item with name XXXX" message after adding a sidebar item, the resulting exit code is a 1 and not a 0 indicating success.  But the item is clearly in the sidebar.

I checked doing this manually via the command line as well with the following: `mysides add example file:///Volumes/example` and I get the same exit code of 1.

I can confirm however that when I run a mysides remove the exit code is 0.

**Comment by mosen** [comment]
Fixed and tagged as v1.0.1. Uploading a pkg.

**Comment by apizz** [comment]
Thank you thank you!  That was fast.  Much appreciated @mosen
